- tls/tls-full/config_template.yaml
- tls/tls-full/docker-compose.yml
- tls/tls-full/generate-certs.sh
Root CA certs should not be included with intermediate CA certs because that leads to undesired successful validation or leaf certs issues by other intermediate CA certs originating from the same root CA.
> Use single intermediate CA certs instead of cert chains with root CA cert

- tls/tls-full/README.md
The file title seemed to be duplicated from the `tls-simple` directory.
> Fixes README instructions

- tls/client-only/README.md
- tls/client-only/alpine/ca.sh
- tls/client-only/alpine/end-entity.sh
- tls/client-only/mac/ca.sh
- tls/client-only/mac/end-entity.sh
I added client-only scripts that support both mac and alpine linux, along with documentation.
Users who have need of client-only certificates may use these.
> Add client-only alpine linux and mac scripts to generate certificates

- README.md
- extensibility/authorizer/README.md
Update a couple of broken documentation links and remove an inconsistent comma in a bullet list.
> Fix stale documentation links

- tls/config/dynamicconfig/development.yaml
- tls/tls-full/README.md
- tls/tls-full/config_template.yaml
- tls/tls-simple/README.md
Added a copy of the standard dynamic config - development.yaml.
Removed duplicate `requireClientAuth` field from config.
Fixed TLS samples, so that they work with the latest version of Temporal.
Removed hardcoded 1.12.4 version from readmes
Manually
No
> Fix TLS sample

- tls/client-only/README.md
- tls/client-only/alpine/end-entity.sh
- tls/client-only/mac/end-entity.sh
- tls/tls-full/README.md
- tls/tls-full/generate-certs.sh
- tls/tls-simple/README.md
- tls/tls-simple/generate-test-certs.sh
This PR adds a step that exports all client-side certificates into .pfx  - standard PKCS12 distribution format. It should help users with bridging our TSL setup examples/documentation with JavaSDK. 
A clarification was added into javadocs about the format of the certificates generated by samples.
https://github.com/temporalio/sdk-java/issues/925
There is a relevant change into JavaSDK that actually adds support for the PFX format. Previously users had to convert PKCS12 into PKCS8 just for JavaSDK: https://github.com/temporalio/sdk-java/pull/941
How was this tested:
Checked that all 3 samples still work and produce an output.
> Add generation of .pfx archives for client certificates

- tls/tls-full/README.md
- tls/tls-full/generate-certs.sh
- tls/tls-simple/README.md
- tls/tls-simple/generate-test-certs.sh
Migrate tls-full and tsl-simple client certs generation to PKCS8
Per discussion in https://github.com/temporalio/samples-server/pull/21
> Update client certificates in both tls-full and tsl-simple to PKCS8

- tls/tls-full/generate-certs.sh
Added an explicit -sha256 flag to openssl commands.
To make sure sha256 is used for signing.
1. Closes
Manually
No
> Add an explicit -sha256 flag

- tls/tls-full/README.md
- tls/tls-full/config_template.yaml
- tls/tls-full/docker-compose.yml
- tls/tls-full/generate-certs.sh
- tls/tls-full/start-temporal.sh
- tls/tls-full/tlsClaimMapper.go
Various improvements to tls-full:
- add diagram of certs
- add notes about ClaimMapper and example that works with this sample
- switched to use internal-frontend to simplify config
- removed systemWorker section and publicClient section
- expose only needed certs+keys to example cli containers
- clean up generate-certs.sh script
Make sample easier to understand and extend
1. Closes 
lots and lots of manual testing (including the example ClaimMapper, although it can't be packaged up nicely due to the sample using docker images)
yes
> Improvements to tls-full sample

- cloud/observability/promql-to-dd-go/worker/utils.go
- cloud/observability/promql-to-dd-go/worker/utils_test.go
- cloud/observability/promql-to-dd-go/worker/worker.go
This PR fixes the previously mistakenly chosen metric type when submitting to Datadog. Rate should be used instead of counter.
1. Closes 
> fix(metric type): Use rate instead of count when submitting metric to Datadog

- cloud/observability/promql-to-dd-go/Dockerfile
- cloud/observability/promql-to-dd-go/helm-charts/templates/deployment.yaml
Use `ENTRYPOINT` to replace `CMD` in promql-to-dd-go Dockerfile.
Requested at: https://github.com/temporalio/samples-server/issues/60
This is to add convenience to run the image as a binary by supplying flags directly without specifying the executable.
1. Closes https://github.com/temporalio/samples-server/issues/60
2. How was this tested: Manually..
> Use ENTRYPOINT instead of CMD to run promqltodd

- cloud/observability/promql-to-nr-ts/README.md
- cloud/observability/promql-to-nr-ts/promql-to-nr.ts
Adds newrelic observability TypeScript example.
I adapted this from the DataDog TypeScript example. Tested it on my own NewRelic account and was able to see the metrics come in.
> add typescript newrelic promql script

- cloud/observability/promql-to-dd-go/helm-charts/templates/deployment.yaml
I've added the ability to override the default `600` seconds in the helm values file.
600 seconds is too infrequent a scrape in some cases.
1. Closes
n/a
Tiny change. No testing.
n/a
> Add query-interval-seconds Helm Chart Override

- cloud/observability/promql-to-scrape/internal/server.go
The previous line acquires a read lock, we should release only the read lock.
> bugfix: Release read lock instead of read-write lock

- cloud/observability/promql-to-dd-go/cmd/promqltodd/main.go
- cloud/observability/promql-to-dd-go/worker/worker.go
Previous, the sleep duration between each data pull/push and the query window was using the same setting/flag.
This PR introduces a new flag to control sleep duration separately and default to 60s. This is also aligned with the Python implementation: https://github.com/temporalio/samples-server/blob/78fbef030e15a022e409fdb6c1e0032940e32f97/cloud/observability/promql-to-dd.py#L62
Output (new default 60 seconds interval):
```
2024/01/22 20:03:37 Submitted total of 2100 series
2024/01/22 20:03:37 Awaits next tick (interval: 60 seconds)
2024/01/22 20:03:48 Querying Prometheus
2024/01/22 20:03:48 Found 1 histogram metrics: [temporal_cloud_v0_service_latency_bucket]
```
1. Closes 
Manual (see above)
> (promql-to-dd-go) add new flag to control sleep duration between runs

- .github/workflows/promql-to-scrape.yaml
- cloud/observability/promql-to-scrape/Dockerfile
Adding GHA workflow to build https://github.com/temporalio/samples-server/tree/main/cloud/observability/promql-to-scrape and publish to https://github.com/orgs/temporalio/packages
1. Closes 
> Add GHA for building promql-to-scrape

- .github/workflows/promql-to-scrape.yaml
Update GHA to use login-action@v3 to login ghcr.io
1. Closes 
> Update GHA to use login-action@v3

- cloud/observability/promql-to-scrape/README.md
Update to more accurately reflect the guidance we give for users of this service.
> update promql-to-scrape README

- extensibility/authorizer/README.md
- extensibility/authorizer/myAuthorizer.go
- extensibility/config/development.yaml
- tls/tls-simple/README.md
- tls/tls-simple/docker-compose.yml
Title says it all.
So the samples work
1. Closes OSS-3851 and OSS-2635
Ran the samples based on READMEs.
should be done in the READMEs already.
> update tls-simple, tls-full, and extensibility authorizer to use ES visibility and temporal cli

- cloud/observability/promql-to-dd-ts/README.md
Deprecated TS scraper, see #106
> recommend datadog's official integration (ts)
